config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home' => 'pages#home'

  get 'pages/ghost'

  get 'pages/end'

  get 'pages/leap'

  get 'pages/boss'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def leap
  end

  def ghost
  end

  def boss
  end

  def end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>BeforeTheDawn</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:600" rel="stylesheet">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/pages/boss.html.erb
<div class="wrapPage">
  <!-- <h1>Effing game thingy</h1> -->
<!-- <h1>LIKE A BAWS</h1> -->
<div class="gameContainer">
<div id="boss"></div>
</div>
</div>

app/views/pages/end.html.erb
<div class="wrapEndPage">
<div class="endContainer">
  <p id="endSpeech">Congratulations on making through to the dawn</p>

  <p id="replay">Restart the Game?</p>
  <div id="button">
    <%= link_to( image_tag(image_path('play_button.png')), pages_leap_path() ) %>
  </div>
</div>
</div>

app/views/pages/ghost.html.erb
<div class="wrapPage">
  <!-- <h1>Blast from the past</h1> -->
  <div class="gameContainer">
    <div id="ghost">

    </div>

  </div>

</div>

app/views/pages/home.html.erb
<section class="panel s1">
	<div id="title">
		<h2>BEFORE THE DAWN</h2>
	</div>
</section>

<!-- <section class="panel s2">
	<div id="title2">
		<h3>It's always the darkest before the dawn</h3>
	</div>
</section>

<section class="panel s3">
	<div class=sectionThree>

	<div id="title3">
		<h3>Sometime in Life, we will...</h3>
	</div>

	<div class="allGames">

		<div class="col col-3">
			<p>Take a Leap Of Faith</p>
			<div class="gameImage">
					<img src="<%= image_path( "leap.gif" ) %>" id="leapSneakPeak" alt="Leap of Faith Game">
			</div>
		</div>

		<div class="col col-3">
			<p>Search for your past</p>
			<div class="gameImage">
					<img src="<%= image_path( "ghost.gif" ) %>" id="ghostSneakPeak" alt="Leap of Faith Game">
			</div>
		</div>

		<div class="col col-3">
			<p>Make a Choice</p>
			<div class="gameImage">
					<img src="<%= image_path( "boss.gif" ) %>" id="bossSneakPeak" alt="Leap of Faith Game">
			</div>
		</div>

	</div>

	</div>
</section> -->


<section class="panel s4">
	<div class="wholePage">
	<div class="startGame">
		<p id="play">Play Game now!</p>
		<div id="button">
		  <%= link_to( image_tag(image_path('play_button.png')), pages_leap_path() ) %>
		</div>

		<div class="allGames">

			<div class="col col-3">
				<p>Level 1</p>
				<p>Leap of Faith</p>
				<div class="gameImage">
						<img src="<%= image_path( "leap.gif" ) %>" id="leapSneakPeak" alt="Leap of Faith Game">
				</div>
			</div>

			<div class="col col-3">
				<p>Level 2</p>
				<p>Blast from the past </p>
				<div class="gameImage">
						<img src="<%= image_path( "ghost.gif" ) %>" id="ghostSneakPeak" alt="Leap of Faith Game">
				</div>
			</div>

			<div class="col col-3">
				<p>Level 3</p>
				<p>Beat the Boss!</p>
				<div class="gameImage">
						<img src="<%= image_path( "boss.gif" ) %>" id="bossSneakPeak" alt="Leap of Faith Game">
				</div>
			</div>

		</div>
	</div>


	</div>
</section>

app/views/pages/leap.html.erb
<div class="wrapPage">
<!-- <h1>Leap of Faith</h1> -->
<div class="gameContainer">
  <div id="leap"></div>
</div>